spring.h2.console.enabled=true
spring.datasource.url=jdbc:h2:mem:bookmycourt_db
# application.properties

# Set DDL-AUTO to 'update' so Hibernate creates/updates tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update

jwt.secret-key=aSuperSecretKeyForSigningTheTokenThatIsAtLeast256BitsLongAndShouldBeVerySecure

# Add this line to your application.properties file
jwt.secret-key=dGhpcyBpcyBhIHZlcnkgc3VwZXIgYW5kIGxvbmcgYW5kIHNlY3VyZSBzZWNyZXQgZm9yIEpXVCBhbmQgc2hvdWxkIGJlIGF0IGxlYXN0IDI1NiBiaXRz
# (This is a sample 256-bit base64-encoded key. You can generate your own.)